# GitHub Action Workflow enforcing our code style.

name: Lint

# Trigger the workflow on both push (to the main repository, on the main branch)
# and pull requests (against the main repository, but from any repo, from any branch).
on:
  push:
    branches:
      - main
  pull_request:
# Brand new concurrency setting! This ensures that not more than one run can be triggered for the same commit.
# It is useful for pull requests coming from the main repository since both triggers will match.
concurrency: lint-${{ github.sha }}

jobs:
  lint-py:
    runs-on: ubuntu-latest

    env:
      # The Python version your project uses. Feel free to change this if required.
      PYTHON_VERSION: "3.10"

    steps:
      # Checks out the repository in the current folder.
      - name: Checks out repository
        uses: actions/checkout@v3

      # Set up the right version of Python
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

  lint-js:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: "16"

    steps:
      - uses: actions/checkout@v3

      - name: Set up NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: cd web/ && npm ci

      - name: Check code
        run: cd web && npm run lint
